### PR TITLE
BL-224 Added thread safety test

### PR DESCRIPTION
**Pull request by sanaullah**
# Description
Thread safety test `testQueryIteratorThreadSafety`

### CODE REVIEW

**Comment by bdw429s** [comment]
This doesn't seem to have anything to do with BL-224.  Is this testing for a specific bug?

**Comment by jclausen** [comment]
@bdw429s It's in regards to your comment and @sanaullah's comment on the previous PR: https://github.com/ortus-boxlang/BoxLang/pull/53#issuecomment-2155315251

**Comment by sanaullah** [comment]
Brad you are right, I think query-data changes are not thread safe. I did another experiment and it failed. so Iterator thread safety issue is still there.

@bdw429s

**Comment by bdw429s** [comment]
@sanaullah Again, the synchronized block in the previous pull does not add "thread safety" to anything (and it needs to be removed).  This new test also does not test thread safety.  This test is designed such that it would pass regardless of whether the iterator was thread safe or not.  (Thread 2 complets in 200 ms, but thread 1 doesn't modify the query until 1000 ms have passed)  An thread safe iterator would need to actually track the internal state of the query and throw a `ConcurrentModificationException` if the query was modified while the iterator was still being used.  To implement this would require more complex changes to the internals of the query object and all its mutators to track a version inside the query that is copied into each iterator.  Every call to `.next()` would need to actually check if the object had changed and then throw the `ConcurrentModificationException` if so.  No synchronization would be necessary for any of that.

The syncronized block you added is just around the actual creation of the iterator, which doesn't actually effect at all how the iterator works once created.  It just prevents two threads from getting an iterator instance at the same time, which isn't something that needs to be thread safe. 

I'm not really a big fan of iterators which throw `ConcurrentModificationException`s because they often times break code looping over shared objects too eagerly.  I'd rather allow the looping and let the CF developers provide their own synchronization at the CF level if they are sharing a query across threads.

**Comment by sanaullah** [comment]
@bdw429s 
Will rollback `synchronized` code, rest is just fixes

**Comment by bdw429s** [comment]
Thanks!

**Pull request merged**
