### PR TITLE
Allow accessing the `this` scope inside threads created in a class.

### PR DESCRIPTION
**Pull request by elpete**

### CODE REVIEW

**Comment by bdw429s** [comment]
I mentioned another way I wanted to solve this in Slack, but after thinking it through, it just adds more potential issues.  If you update this to check for a ClassBoxContext as well, I'll merge it. 

Then you can add the same checks to the `CustomTagBoxContext` so it can illegally "see" the `this` scope as well :)

**Comment by elpete** [comment]
@bdw429s Added.

**Comment by elpete** [comment]
The `this` scope is *not* discoverable in Adobe or Lucee.  So remove that portion from the method?

**Comment by bdw429s** [comment]
Yes please.  Keep the parts that check if the incoming key is literally "this", but remove the checks that search inside of the `this` scope for unscoped variables.

**Comment by bdw429s** [comment]
@elpete Had a chance to finalize this?

**Pull request merged**
