### PR TITLE
BL-224

### PR DESCRIPTION
**Pull request by sanaullah**
# Description

Fixed Iterator and thread safety 

https://ortussolutions.atlassian.net/browse/BL-224

### CODE REVIEW

**Comment by sanaullah** [comment]
@lmajano Please I require your help, bit difficult to find out what failed for ubuntu.

**Comment by jclausen** [comment]
@sanaullah The error is a weird one we've seen before with `Path` not being available.  Re-running the job usually fixes.  I kicked it off.

**Comment by jclausen** [comment]
Looks like it failed again.  Something in that actions runner doesn't expose a `PATH` environment variable.   That test usually works, but it fails sometimes.  I'm going to merge this as your commits have no effect on that test failing.

**Comment by bdw429s** [comment]
@jclausen @sanaullah I don't believe this code actually does anything to make the iterator thread safe. All you've done is wrapped the creation of the iterator, but in order for the iterator itself to be threadsafe, wouldn't the implementation methods inside of it need to somehow ensure the underlying query had not been modified while records were being fetched? The synchronized block doesn't change the actual iterator itself at all-- only ensure one thread at a time can create an iterator, but that is not an operation that requires thread safety.

**Comment by sanaullah** [comment]
I just added another thread test `testQueryIteratorThreadSafety`
thread1 is adding data and while other thread2 reading the data. The iterator returned 2 records which look correct.
Pushing test case for your review

@bdw429s @jclausen

**Pull request merged**
